#!/bin/sh /etc/rc.common

START=85
STOP=10
USE_PROCD=1

start_service() {
	[ "$(uci -q get mesh_agent.main.enabled)" = "1" ] || return 0
	mkdir -p /etc/mesh-agent
	procd_open_instance
	procd_set_param command /usr/sbin/mesh-agent
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	restart
}
