#!/bin/sh

/etc/init.d/umdns enable >/dev/null 2>&1 || true

if [ -f /etc/config/easymesh ]; then
	uci -q set easymesh_agent.main.enabled='0'
	uci -q commit easymesh_agent
	/etc/init.d/easymesh-agent disable >/dev/null 2>&1 || true
	/etc/init.d/easymesh-backhaul enable >/dev/null 2>&1 || true
else
	/usr/sbin/easymesh-agent-apply --network-only >/dev/null 2>&1 || true
	/etc/init.d/easymesh-agent enable >/dev/null 2>&1 || true
	/etc/init.d/easymesh-backhaul enable >/dev/null 2>&1 || true
fi

exit 0
